### ISSUE TITLE
doc: More detailed build instructions for hostapd

### ISSUE THREAD

**Issue by ankostis** [pritambaral/hostapd-rtl871xdrv#14]
Building `hostapd` requires `openssl` header files.
Under *Debian*, this is easily accomplished by running:

    sudo apt install libssl-dev

It might be good to add this tip to the `README.md` since `make` command is suggested.

**Comment by pritambaral** [comment]
This is not a `hostapd` repo. I'd rather not have to maintain build instructions for various distros and configs (except this driver). I will shortly amend the README to remove any build instructions except patching.

**Comment by ankostis** [comment]
Right choice; but now that you are at it, correct also the link to hostapd-site: http://w1.fi/hostapd/

By the, way: did you try to submit this patch to `hostapd` and it was rejected?

**Comment by pritambaral** [comment]
@ankostis Link has been updated on master, won't update on old tags.

Haven't submitted to `hostapd`, because I am strongly against this poorly written, non-standard driver being included in and having to be maintained by mainline hostapd. I'd much prefer the mainline driver in the kernel gain stable `nl80211` support.
